name: Publish docker image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
      - name: Build
        run: |
          bun run build:web && bun run build:server
          mv ./dist app
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rssarr-${{ github.ref_name }}
          path: |
            ./app
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        if: github.event_name == 'release'
        with:
          type: 'zip'
          filename: "rssarr-${{ github.ref_name }}.zip"
          directory: ./app
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./app/rssarr-${{ github.ref_name }}.zip"
          asset_name: rssarr-${{ github.ref_name }}.zip
          tag: ${{ github.ref }}

  build-docker:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: rssarr-${{ github.ref_name }}
          path: ./app
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: list dir
        run: |
          ls -la
          ls -la ./app

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          context: .
          file: ./Dockerfile.ci
          push: true
          tags: |
            izumiko/rssarr:latest
            izumiko/rssarr:${{ github.ref_name }}